W7D3/music_app/config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     users POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#                   session DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#                     bands GET    /bands(.:format)                                                                         bands#index
#                           POST   /bands(.:format)                                                                         bands#create
#                  new_band GET    /bands/new(.:format)                                                                     bands#new
#                 edit_band GET    /bands/:id/edit(.:format)                                                                bands#edit
#                      band GET    /bands/:id(.:format)                                                                     bands#show
#                           PATCH  /bands/:id(.:format)                                                                     bands#update
#                           PUT    /bands/:id(.:format)                                                                     bands#update
#                           DELETE /bands/:id(.:format)                                                                     bands#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy]
end

W7D3/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D3/music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true
end

W7D3/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

    validates :email, :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }
    validates :password_digest, presence: { message: "Password can't be blank"}

    after_initialize do |user|
        user.ensure_session_token
    end

    attr_reader :password

    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            return user
        else
            return nil
        end
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

end

W7D3/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

W7D3/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def create
        @band = Band.create(band_params)
        if @band.save
            debugger
            redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        @band = Band.find(params[:id])
        if @band
            render :edit
        else
            flash.now[:errors] = @band.errors.full_messages
            redirect_to new_band_url
        end
    end

    def update
        @band = Band.find(params[:id])
        if @band.update_attributes(band_params)
            redirect_to band_url(@band)
        else
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private 

    def band_params
        params.require(:band).permit(:name)
    end
end

W7D3/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(
            params[:session][:user][:email],
            params[:session][:user][:password]
        )
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

W7D3/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.new[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

W7D3/music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

W7D3/music_app/app/views/bands/edit.html.erb
<h1>Edit-A-Band</h1>

<form class="ui form" action="<%= band_url(@band) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">

    <input type="text" name=band[name] value="<%= @band.name %>" placeholder="Band Name">

    <input type="submit" class="ui button" value="Edit Band">
</form>

W7D3/music_app/app/views/bands/index.html.erb
<ul>
    <% @bands.each do |band| %>
        <li>
            <%= band.name %>
        </li>
    <% end %>
</ul>

W7D3/music_app/app/views/bands/new.html.erb
<h1>Build-A-Band</h1>

<form class="ui form" action="<%= bands_url %>" method="POST">

    <input type="text" name=band[name] value="<%= @band.name %>" placeholder="Band Name">

    <input type="submit" class="ui button" value="Create Band">
</form>

W7D3/music_app/app/views/bands/show.html.erb
<%= @band.name %>

W7D3/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
  </head>

  <body class="ui container">
  <header style="display:flex;justify-content:space-between;">
  <h1>MUSIC APP</h1>
    <div>
      <% if logged_in? %>

        <form action="<%= session_url %>" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <input class="ui button" type="submit" value="Logout">
        </form>

      <% end %>

      <% unless logged_in? %>

        <a  class="ui button" href="<%= new_user_url %>">Sign-Up</a>
        <a  class="ui button" href="<%= new_session_url %>">Log In</a>

      <% end %>
  </div>
  </header>
    <%= yield %>
  </body>
</html>

W7D3/music_app/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form class="ui form" action="<%= users_url %>" method="POST">
    <input type="text" name=user[email] value="<%= @user.email %>" placeholder="Email">
    
    <input type="password" name=user[password] value="" placeholder="Password">

    <input class="ui button" type="submit" value="Sign-Up">
</form>

W7D3/music_app/app/views/users/show.html.erb
<%= @user.email %>